In [1]:
%matplotlib  inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
data_1 = pd.read_csv('Контракты 44ФЗ.csv', sep=';')
data_2 = pd.read_csv('Справочник пром производства.csv', sep=';')
data_3 = pd.read_csv('Ценовые предложения поставщиков.csv', sep=';')

In [3]:
data_1.head()

,product_name,price,product_vat_rate,product_msr,product_characteristics,okpd2_code,okpd2_name,inn,country_code
0,Драм-юнит Cet CET8997,7605.00,0%,Штука,NaN,28.23.25.000,Части и принадлежности прочих офисных машин,6a2325da490021b46bb00834ab4a560a,156
1,Лук репчатый,48.75,Без НДС,Килограмм,Дополнительные показатели (характеристики): Ук...,01.13.43.110,Лук репчатый,c8f328b188e78a1673db8cc2db1b6828,643
2,Карандаш механический (Страна происхождения : ...,8.00,20%,Штука,NaN,32.99.12.130,Карандаши механические,9d785973706feeff180ee96a247135e6,156
3,Имплантаты для остеосинтеза варианты исполнени...,5200.00,Без НДС,Штука,NaN,32.50.50.190,"Изделия медицинские, в том числе хирургические...",5a35794bbd7c29420b25479364c26c7b,616
4,Говядина замороженная для детского питания,490.59,Без НДС,Килограмм,NaN,10.11.31.130,Говядина и телятина замороженные для детского ...,91c23daf46d288344828eac627074bf3,643

In [4]:
data_1.shape

(1000, 9)

In [5]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   product_name             1000 non-null   object
 1   price                    1000 non-null   float64
 2   product_vat_rate         1000 non-null   object
 3   product_msr              1000 non-null   object
 4   product_characteristics  297 non-null    object
 5   okpd2_code               1000 non-null   object
 6   okpd2_name               1000 non-null   object
 7   inn                      1000 non-null   object
 8   country_code             992 non-null    object
dtypes: float64(1), object(8)
memory usage: 70.4+ KB

In [6]:
data_1['price'].describe()

count    1.000000e+03
mean     2.530439e+04
std      3.118873e+05
min      7.000000e-02
25%      4.999250e+01
50%      2.622000e+02
75%      1.975230e+03
max      7.947255e+06
Name: price, dtype: float64

In [7]:
data_1["price"].value_counts()

220.00    5
125.00    4
8.00      4
225.00    4
3.00      4
         ..
41.65     1
45.77     1
100.80    1
9.30      1
9.08      1
Name: price, Length: 911, dtype: int64

In [8]:
data_1["price"].mean()

25304.38696254347

In [9]:
data_1['country_code'].value_counts()

643                            702
156                             95
840                             39
276                             27
356                              7
                              ...
276|840                          1
208                              1
756|840                          1
380|276|756|840|826              1
356|156|440|372|158|840|826      1
Name: country_code, Length: 73, dtype: int64

In [10]:
data_1['product_name'].value_counts().head()

Бланки форм учетной и отчетной документации                                                                  11
Учебники печатные общеобразовательного назначения                                                             9
Инструменты и приспособления, применяемые в медицинских целях, прочие, не включенные в другие группировки     8
Катетер баллонный для коронарной ангиопластики, стандартный                                                   5
Крупа гречневая                                                                                               5
Name: product_name, dtype: int64

In [11]:
all_words = np.concatenate(data_1["product_name"].apply(lambda s: s.strip().split()).values)

In [12]:
pd.Series(list(all_words)).value_counts()

для            223
и              109
с               97
в               95
-               68
              ...
изделий          1
совмещенной      1
очисткой,        1
ручным           1
чистки           1
Length: 3943, dtype: int64

In [13]:
len(all_words)

7640

In [14]:
import nltk

In [15]:
from nltk.corpus import stopwords

In [16]:
words_series = pd.Series(list(all_words))
words_series[~words_series.isin(nltk.corpus.stopwords.words("russian"))].value_counts().head(20)

-                68
Набор            41
2                35
1                31
класс.           29
ИВД,             26
В                23
реагентов        22
–                22
назначения       21
Журнал           21
использования    21
определения      20
происхождения    18
х                18
мм               17
Крупа            17
Россия           16
крови            15
Перчатки         15
dtype: int64

In [17]:
data_1['product_msr'].value_counts()

Штука                               547
Килограмм                           169
Набор                                70
Упаковка                             62
Литр кубический дециметр             39
Метр                                 19
Пара (2 шт.)                         19
Кубический метр                      12
Флакон                                8
Погонный метр                         8
Гигакалория                           8
Киловатт-час                          7
Комплект                              6
Пачка                                 5
Мегаватт-час 1000 киловатт-часов      3
Номер                                 3
Условная единица                      2
Киловатт                              2
Тысяча кубических метров              2
Квадратный метр                       2
Рулон                                 2
Бутылка                               2
Дето-день                             1
Бобина                                1
Гигакалория в час                     1
Name: product_msr, dtype: int64

In [18]:
data_2.head()

,product_name,price,product_vat_rate,product_msr,product_characteristics,okpd2_code,okpd2_name,inn,country_code
0,Натрий двууглекислый,NaN,Без НДС,Тонна метрическая тонна (1000 кг),Описание: Натрий двууглекислый || Массовая дол...,20.13.43,Карбонаты,22f5fd1c91e58e210ee693fd834b0ffa,643.0
1,Гидрокарбонат натрия. Пищевая добавка E500(ii),NaN,Без НДС,Тонна метрическая тонна (1000 кг),Описание: Гидрокарбонат натрия. Пищевая добавк...,20.13.43.191,Водородкарбонат натрия (бикарбонат натрия),22f5fd1c91e58e210ee693fd834b0ffa,643.0
2,маневровый тепловоз ТЭМ18ДМ,NaN,Без НДС,Штука,Описание: маневровый тепловоз ТЭМ18ДМ || Мощно...,30.20.12.120,Тепловозы маневровые и промышленные,21578d9b4a3c742d2a450e89dafe3e54,643.0
3,Тепловоз магистральный грузовой двухсекционный...,NaN,Без НДС,Секция,Описание: Тепловоз магистральный грузовой двух...,30.20.12.110,Тепловозы магистральные,21578d9b4a3c742d2a450e89dafe3e54,643.0
4,Универсальный фронтальный мини-погрузчик с бор...,NaN,Без НДС,Штука,Описание: Универсальный фронтальный мини-погру...,28.92.25.000,Погрузчики фронтальные одноковшовые самоходные,23dfc06d1aa3f159711b0833da1310cc,643.0

In [19]:
data_2.shape

(1000, 9)

In [20]:
data_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   product_name             1000 non-null   object
 1   price                    117 non-null    float64
 2   product_vat_rate         1000 non-null   object
 3   product_msr              1000 non-null   object
 4   product_characteristics  1000 non-null   object
 5   okpd2_code               1000 non-null   object
 6   okpd2_name               1000 non-null   object
 7   inn                      1000 non-null   object
 8   country_code             890 non-null    float64
dtypes: float64(2), object(7)
memory usage: 70.4+ KB

In [21]:
data_2['price'].describe()

count    1.170000e+02
mean     1.441466e+06
std      2.204271e+06
min      0.000000e+00
25%      2.897500e+03
50%      2.000000e+06
75%      2.300000e+06
max      1.400000e+07
Name: price, dtype: float64

In [22]:
data_2["price"].value_counts().head()

2250000.00    15
2333333.33    15
8333.33       11
2000000.00     8
2300000.00     7
Name: price, dtype: int64

In [23]:
data_2["price"].mean()

1441465.849458691

In [24]:
data_2['country_code'].value_counts()

643.0    890
Name: country_code, dtype: int64

In [25]:
data_3.head()

,product_name,price,product_vat_rate,product_msr,product_characteristics,okpd2_code,okpd2_name,inn,country_code
0,"Мешки для мусора 240 л, черные, ПВД, 100 мкм, ...",24.22,20%,Штука,Объем: 240.0л дм[3*] || Вид материала: ПВД || ...,22.22.1,Изделия пластмассовые упаковочные,8862f4d4ee368febd5fac195c84f8dde,NaN
1,Степ платформа,4340.98,Без НДС,Штука,Описание: Степ платформа || Виды товаров спорт...,32.30.14.129,"Оборудование для занятий физкультурой, гимнаст...",605fc8ce2b603efc77cefa563781105f,156.0
2,Скобы для степлера,114.00,Без НДС,Штука,Описание: Скобы для степлера || Количество в у...,25.99.23.000,"Детали для скоросшивателей или папок, канцеляр...",766fe416835260900f67379de663439c,NaN
3,"Эмаль Vika МЛ-1110 Апельсин Камаз 0,8 кг",709.00,Без НДС,Штука,Тип краски: Однокомпонентная синтетическая эма...,29.32.30.390,Части и принадлежности для автотранспортных ср...,71b52ca820c667fb8cebd3fcf362ac79,643.0
4,Средство дезинфицирующее Део-бактер 1л,499.00,20%,Флакон,Объем: 1л дм[3*] || Действующие вещества: ЧАС ...,20.20.14.000,Средства дезинфекционные,c2c3bea3f9fe8262cea420f1b6d3772b,NaN

In [26]:
data_3.shape

(1000, 9)

In [27]:
data_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   product_name             1000 non-null   object
 1   price                    1000 non-null   float64
 2   product_vat_rate         1000 non-null   object
 3   product_msr              1000 non-null   object
 4   product_characteristics  1000 non-null   object
 5   okpd2_code               1000 non-null   object
 6   okpd2_name               1000 non-null   object
 7   inn                      1000 non-null   object
 8   country_code             705 non-null    float64
dtypes: float64(2), object(7)
memory usage: 70.4+ KB

In [28]:
data_3['price'].describe()

count      1000.000000
mean       7154.309280
std       29194.168089
min           0.500000
25%         187.800000
50%         687.100000
75%        3278.390000
max      623500.000000
Name: price, dtype: float64

In [29]:
data_3["price"].value_counts()

350.00      7
37.80       7
500.00      6
260.00      5
1000.00     5
           ..
18019.00    1
243.00      1
79.00       1
635.64      1
9.65        1
Name: price, Length: 881, dtype: int64

In [30]:
data_3["price"].mean()

7154.3092799999995

In [31]:
data_3['country_code'].value_counts().head()

643.0    505
156.0    110
276.0     23
392.0      9
112.0      6
Name: country_code, dtype: int64